name: Cross compile AWGProxy

on:
  workflow_dispatch:
  create:
     tags:
       - v*

jobs:
  AWGProxy:

    name: Cross compile AWGProxy

    runs-on: ubuntu-latest

    env:
      workdir: ./AWGProxy

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Git clone AWGProxy
        run: |
          git clone https://github.com/mishamosher/awgproxy.git ${{ env.workdir }}
          cp ./.github/awgproxy-releaser.yml ${{ env.workdir }}/.goreleaser.yml

      - name: Set up GoReleaser
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          workdir: ${{ env.workdir }}
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release binaries
        uses: softprops/action-gh-release@v1
        with:
          tag_name: awgproxy
          files: ${{ env.workdir }}/dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
